version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
#    ports:
#      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: odoo:15.0
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
  
volumes:
  db-data:
  web-data: